core/objects/RoundRobin__c/RoundRobin__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Round Robin</label>
</CustomObject>

core/objects/RoundRobin__c/fields/LastUpdated__c.field-meta.xml
<CustomField>
    <fullName>LastUpdated__c</fullName>
    <label>Last Updated</label>
    <type>DateTime</type>
</CustomField>

core/classes/RoundRobinRepositoryTests.cls
@IsTest
private class RoundRobinRepositoryTests {
  private static String cacheKey = 'a sales team';
  @IsTest
  static void shouldUpdateAssignment() {
    Datetime someTimeAgo = System.now().addDays(-3);
    upsert new RoundRobin__c(LastUpdated__c = someTimeAgo, Name = cacheKey);
    RoundRobinRepository repo = new RoundRobinRepository();

    repo.accept(new VisitorMock(), new List<SObject>());

    RoundRobin__c updatedAssignment = [SELECT LastUpdated__c FROM RoundRobin__c WHERE Name = :cacheKey];
    System.assertEquals(
      true,
      someTimeAgo < updatedAssignment.LastUpdated__c,
      'Cached record should have had its LastUpdated__c field updated properly: ' + updatedAssignment
    );
  }

  private class VisitorMock implements IThreadSafeCacheVisitor {
    public String getVisitKey() {
      return cacheKey;
    }
    public void visitRecords(List<SObject> records, SObject currentCacheRecord) {
      // no-op
    }
  }
}